language: ruby
cache: bundler
rvm: 2.5
addons:
  postgresql: '9.5'
install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} --without development
before_script:
  - export SECRET_KEY_BASE=`bundle exec rake secret`
  - cp config/database.yml.travis config/database.yml
  - python -c 'import multiprocessing;print(multiprocessing.cpu_count())'
  - bundle exec rake "parallel:setup[2]"
script:
  - bundle exec rake "parallel:spec[2]" lint
